version: "3.8"

services:
  sonarqube:
    image: sonarqube:8.9.7-community
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
    - 'SonarQube_data:/opt/SonarQube/data'
    - 'SonarQube_extensions : /opt/SonarQube/extensions'
    - 'SonarQube_logs:/opt/SonarQube/logs'
    restart: unless-stopped
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
    - 'nexus-data:/nexus-data'
    restart: unless-stopped
  mysql:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    volumes:
    - 'mysql-data:/var/lib/mysql'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: tpachato
      MYSQL_USER: root
      MYSQL_PASSWORD: 

volumes:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  nexus-data: